#:kivy 2.0.0

<TWTextInput@TextInput>:
    readonly: True

<TWLabel@Label>:
    size_hint_y: 0.1

<TextsWidget>:
    plain_text_box: plain_text_box
    ssml_box: ssml_box
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'
        TWLabel:
            text: 'Plain Text'
        TWTextInput:
            id: plain_text_box
        TWLabel:
            text: 'ssml'
        TWTextInput:
            id: ssml_box

